version: "3.1"

services:
 php-fpm:
    build: docker/php-fpm
    working_dir: /application
    volumes:
      - .:/application
    ports:
      - '80:80'
      - '9500:9500'
 redis:
   image: redis:alpine
   ports:
     - '6379:6379'
   volumes:
     - 'swoole-redis:/data'
   healthcheck:
     test: [ "CMD", "redis-cli", "ping" ]

volumes:
  swoole-redis:
    driver: local